[app]
host = "0.0.0.0"
port = 8000
reload = false
debug = false

[database]
postgres_username = "postgres"
postgres_db = "postgres"
postgres_port = 5432
postgres_host = "localhost"
postgres_password = "postgres"
echo = true
