from typing import Protocol
import uuid

from src.core.db import models


class ChecklistItemRepository(Protocol):
    async def get_by_id(self, checklist_item_id: uuid.UUID) -> models.ChecklistItem | None: ...
    async def create(self, data: dict) -> models.ChecklistItem: ...
    async def update(self, checklist_item_id: uuid.UUID, data: dict) -> models.ChecklistItem: ...
    async def delete(self, checklist_item_id: uuid.UUID) -> None: ...
    async def list_by_checklist(self, checklist_id: uuid.UUID) -> list[models.ChecklistItem]: ...

class ChecklistRepository(Protocol):
    async def get_by_id(self, checklist_id: uuid.UUID) -> models.Checklist | None: ...
    async def create(self, data: dict) -> models.Checklist: ...
    async def update(self, checklist_id: uuid.UUID, data: dict) -> models.Checklist: ...
    async def delete(self, checklist_id: uuid.UUID) -> None: ...

class CommentRepository(Protocol):
    async def get_by_id(self, comment_id: uuid.UUID) -> models.Comment | None: ...
    async def create(self, data: dict) -> models.Comment: ...
    async def update(self, comment_id: uuid.UUID, data: dict) -> models.Comment: ...
    async def delete(self, comment_id: uuid.UUID) -> None: ...
    async def list_by_task_id(self, task_id: uuid.UUID) -> list[models.Comment]: ...

class ProjectMemberRepository(Protocol):
    async def get(self, project_id: uuid.UUID, user_id: uuid.UUID) -> models.ProjectMember | None: ...
    async def create(self, data: dict) -> models.ProjectMember: ...
    async def update(self, project_id: uuid.UUID, user_id: uuid.UUID, data: dict) -> models.ProjectMember: ...
    async def delete(self, project_id: uuid.UUID, user_id: uuid.UUID) -> None: ...
    async def list_by_project(self, project_id: uuid.UUID) -> list[models.ProjectMember]: ...
    async def list_by_user(self, user_id: uuid.UUID) -> list[models.ProjectMember]: ...

class ProjectRepository(Protocol):
    async def get_by_id(self, project_id: uuid.UUID) -> models.Project | None: ...
    async def create(self, data: dict) -> models.Project: ...
    async def update(self, project_id: uuid.UUID, data: dict) -> models.Project: ...
    async def delete(self, project_id: uuid.UUID) -> None: ...

class StatusRepository(Protocol):
    async def get_by_id(self, status_id: uuid.UUID) -> models.Status | None: ...
    async def create(self, data: dict) -> models.Status: ...
    async def update(self, status_id: uuid.UUID, data: dict) -> models.Status: ...
    async def delete(self, status_id: uuid.UUID) -> None: ...
    async def list_by_project(self, project_id: uuid.UUID) -> list[models.Status]: ...

class TagRepository(Protocol):
    async def get_by_id(self, tag_id: uuid.UUID) -> models.Tag | None: ...
    async def create(self, data: dict) -> models.Tag: ...
    async def update(self, tag_id: uuid.UUID, data: dict) -> models.Tag: ...
    async def delete(self, tag_id: uuid.UUID) -> None: ...
    async def list_by_project(self, project_id: uuid.UUID) -> list[models.Tag]: ...

class TaskSequenceRepository(Protocol):
    async def get_by_project(self, project_id: uuid.UUID) -> models.TaskSequence | None: ...
    async def create(self, data: dict) -> models.TaskSequence: ...
    async def update_by_project(self, project_id: uuid.UUID, data: dict) -> models.TaskSequence: ...
    async def delete_by_project(self, project_id: uuid.UUID) -> None: ...

class TaskTagRepository(Protocol):
    async def get(self, task_id: uuid.UUID, tag_id: uuid.UUID) -> models.TaskTag | None: ...
    async def create(self, task_id: uuid.UUID, tag_id: uuid.UUID) -> models.TaskTag: ...
    async def delete(self, task_id: uuid.UUID, tag_id: uuid.UUID) -> None: ...
    async def list_by_task(self, task_id: uuid.UUID) -> list[models.TaskTag]: ...
    async def list_by_tag(self, tag_id: uuid.UUID) -> list[models.TaskTag]: ...

class TaskRepository(Protocol):
    async def get_by_id(self, task_id: uuid.UUID) -> models.Task | None: ...
    async def create(self, data: dict) -> models.Task: ...
    async def update(self, task_id: uuid.UUID, data: dict) -> models.Task: ...
    async def delete(self, task_id: uuid.UUID) -> None: ...
    async def list_by_project(self, project_id: uuid.UUID) -> list[models.Task]: ...
    async def list_by_status(self, status_id: uuid.UUID) -> list[models.Task]: ...

class UserRepository(Protocol):
    async def get_by_id(self, user_id: uuid.UUID) -> models.User | None: ...
    async def create(self, data: dict) -> models.User: ...
    async def update(self, user_id: uuid.UUID, data: dict) -> models.User: ...
    async def delete(self, user_id: uuid.UUID) -> None: ...
    async def list_all(self) -> list[models.User]: ...
