from typing import Protocol, TypeVar, Generic, Tuple
import uuid

from src.core.db import models, Base

T = TypeVar("T", bound=Base)


class BaseRepository(Protocol, Generic[T]):
    async def get_by_id(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID]) -> T | None: ...
    async def create(self, data: dict) -> T: ...
    async def update(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID], data: dict) -> T: ...
    async def delete(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID]) -> None: ...
    async def get_all(self) -> list[T]: ...


class StoreProtocol(Protocol):
    checklist_items: BaseRepository[models.ChecklistItem]
    checklists: BaseRepository[models.Checklist]
    comments: BaseRepository[models.Comment]
    project_members: BaseRepository[models.ProjectMember]
    projects: BaseRepository[models.Project]
    statuses: BaseRepository[models.Status]
    tags: BaseRepository[models.Tag]
    tasks: BaseRepository[models.Task]
    task_sequences: BaseRepository[models.TaskSequence]
    task_tags: BaseRepository[models.TaskTag]
    users: BaseRepository[models.User]

    def checklist_item_repo(self) -> BaseRepository[models.ChecklistItem]: ...
    def checklist_repo(self) -> BaseRepository[models.Checklist]: ...
    def comment_repo(self) -> BaseRepository[models.Comment]: ...
    def project_member_repo(self) -> BaseRepository[models.ProjectMember]: ...
    def project_repo(self) -> BaseRepository[models.Project]: ...
    def status_repo(self) -> BaseRepository[models.Status]: ...
    def tag_repo(self) -> BaseRepository[models.Tag]: ...
    def task_repo(self) -> BaseRepository[models.Task]: ...
    def task_sequence_repo(self) -> BaseRepository[models.TaskSequence]: ...
    def task_tag_repo(self) -> BaseRepository[models.TaskTag]: ...
    def user_repo(self) -> BaseRepository[models.User]: ...
