import uuid
from typing import Generic, Tuple, TypeVar
from abc import ABC, abstractmethod

from src.core.db import Base, models

T = TypeVar("T", bound=Base)


# noinspection DuplicatedCode
class BaseRepository(ABC, Generic[T]):
    @abstractmethod
    async def get_by_id(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID]) -> T | None: ...
    @abstractmethod
    async def create(self, data: dict) -> T: ...
    @abstractmethod
    async def update(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID], data: dict) -> T: ...
    @abstractmethod
    async def delete(self, item_id: uuid.UUID | Tuple[uuid.UUID, uuid.UUID]) -> None: ...
    @abstractmethod
    async def get_all(self) -> list[T]: ...


class Store(ABC):
    checklist_items: BaseRepository[...]
    checklists: BaseRepository[...]
    comments: BaseRepository[...]
    project_members: BaseRepository[...]
    projects: BaseRepository[...]
    statuses: BaseRepository[...]
    tags: BaseRepository[...]
    tasks: BaseRepository[...]
    task_sequences: BaseRepository[...]
    task_tags: BaseRepository[...]
    users: BaseRepository[...]

    def checklist_item_repo(self) -> BaseRepository[...]: ...
    def checklist_repo(self) -> BaseRepository[...]: ...
    def comment_repo(self) -> BaseRepository[...]: ...
    def project_member_repo(self) -> BaseRepository[...]: ...
    def project_repo(self) -> BaseRepository[...]: ...
    def status_repo(self) -> BaseRepository[...]: ...
    def tag_repo(self) -> BaseRepository[...]: ...
    def task_repo(self) -> BaseRepository[...]: ...
    def task_sequence_repo(self) -> BaseRepository[...]: ...
    def task_tag_repo(self) -> BaseRepository[...]: ...
    def user_repo(self) -> BaseRepository[...]: ...
