"""update models for cascade and UUID defaults

Revision ID: 85c0c9db9d8d
Revises: 64e4f5641a1a
Create Date: 2025-11-23 20:15:51.243806+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy import text

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85c0c9db9d8d"
down_revision: str | Sequence[str] | None = "64e4f5641a1a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("checklist_task_id_fkey"), "checklist", type_="foreignkey")
    op.create_foreign_key("checklist_task_id_fkey", "checklist", "task", ["task_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("checklistitem_checklist_id_fkey"), "checklistitem", type_="foreignkey")
    op.create_foreign_key(
        "checklistitem_checklist_id_fkey", "checklistitem", "checklist", ["checklist_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("comment_task_id_fkey"), "comment", type_="foreignkey")
    op.create_foreign_key("comment_task_id_fkey", "comment", "task", ["task_id"], ["id"], ondelete="CASCADE")
    op.create_unique_constraint("uq_projectmember_project_id_user_id", "projectmember", ["project_id", "user_id"])
    op.drop_constraint(op.f("projectmember_project_id_fkey"), "projectmember", type_="foreignkey")
    op.create_foreign_key(
        "projectmember_project_id_fkey", "projectmember", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_constraint(op.f("status_project_id_fkey"), "status", type_="foreignkey")
    op.create_foreign_key("status_project_id_fkey", "status", "project", ["project_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("tag_project_id_fkey"), "tag", type_="foreignkey")
    op.create_foreign_key("tag_project_id_fkey", "tag", "project", ["project_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("task_project_id_fkey"), "task", type_="foreignkey")
    op.drop_constraint(op.f("task_status_id_fkey"), "task", type_="foreignkey")
    op.create_foreign_key("task_status_id_fkey", "task", "status", ["status_id"], ["id"], ondelete="RESTRICT")
    op.create_foreign_key("task_project_id_fkey", "task", "project", ["project_id"], ["id"], ondelete="CASCADE")
    op.drop_constraint(op.f("tasksequence_project_id_fkey"), "tasksequence", type_="foreignkey")
    op.create_foreign_key(
        "tasksequence_project_id_fkey", "tasksequence", "project", ["project_id"], ["id"], ondelete="CASCADE"
    )
    op.create_unique_constraint("uq_tasktag_task_id_tag_id", "tasktag", ["task_id", "tag_id"])
    op.drop_constraint(op.f("tasktag_tag_id_fkey"), "tasktag", type_="foreignkey")
    op.drop_constraint(op.f("tasktag_task_id_fkey"), "tasktag", type_="foreignkey")
    op.create_foreign_key("tasktag_tag_id_fkey", "tasktag", "tag", ["tag_id"], ["id"], ondelete="CASCADE")
    op.create_foreign_key("tasktag_task_id_fkey", "tasktag", "task", ["task_id"], ["id"], ondelete="CASCADE")
    tables = [
        "checklistitem", "checklist", "comment", "project", "status", "tag", "task", "usr" 
    ]
    for table in tables:
        op.alter_column(
            table, "id",
            server_default=text("gen_random_uuid()"),
            existing_type=sa.dialects.postgresql.UUID(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("tasktag_task_id_fkey", "tasktag", type_="foreignkey")
    op.drop_constraint("tasktag_tag_id_fkey", "tasktag", type_="foreignkey")
    op.create_foreign_key(op.f("tasktag_task_id_fkey"), "tasktag", "task", ["task_id"], ["id"])
    op.create_foreign_key(op.f("tasktag_tag_id_fkey"), "tasktag", "tag", ["tag_id"], ["id"])
    op.drop_constraint("uq_tasktag_task_id_tag_id", "tasktag", type_="unique")
    op.drop_constraint("tasksequence_project_id_fkey", "tasksequence", type_="foreignkey")
    op.create_foreign_key(
        op.f("tasksequence_project_id_fkey"), "tasksequence", "project", ["project_id"], ["id"]
    )
    op.drop_constraint("task_status_id_fkey", "task", type_="foreignkey")
    op.drop_constraint("task_project_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(op.f("task_status_id_fkey"), "task", "status", ["status_id"], ["id"])
    op.create_foreign_key(op.f("task_project_id_fkey"), "task", "project", ["project_id"], ["id"])
    op.drop_constraint("tag_project_id_fkey", "tag", type_="foreignkey")
    op.create_foreign_key(op.f("tag_project_id_fkey"), "tag", "project", ["project_id"], ["id"])
    op.drop_constraint("status_project_id_fkey", "status", type_="foreignkey")
    op.create_foreign_key(
        op.f("status_project_id_fkey"), "status", "project", ["project_id"], ["id"]
    )
    op.drop_constraint("projectmember_project_id_fkey", "projectmember", type_="foreignkey")
    op.create_foreign_key(
        op.f("projectmember_project_id_fkey"), "projectmember", "project", ["project_id"], ["id"]
    )
    op.drop_constraint("uq_projectmember_project_id_user_id", "projectmember", type_="unique")
    op.drop_constraint("comment_task_id_fkey", "comment", type_="foreignkey")
    op.create_foreign_key(op.f("comment_task_id_fkey"), "comment", "task", ["task_id"], ["id"])
    op.drop_constraint("checklistitem_checklist_id_fkey", "checklistitem", type_="foreignkey")
    op.create_foreign_key(
        op.f("checklistitem_checklist_id_fkey"),
        "checklistitem",
        "checklist",
        ["checklist_id"],
        ["id"],
    )
    op.drop_constraint("checklist_task_id_fkey", "checklist", type_="foreignkey")
    op.create_foreign_key(op.f("checklist_task_id_fkey"), "checklist", "task", ["task_id"], ["id"])
    tables = [
        "checklistitem", "checklist", "comment", "project", "status", "tag", "task", "usr" 
    ]
    for table in tables:
        op.alter_column(
            table, "id",
            server_default=None,
            existing_type=sa.dialects.postgresql.UUID(),
            existing_nullable=False,
        )
    # ### end Alembic commands ###
